# Generated by Django 4.0.4 on 2022-06-07 16:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0008_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='videos',
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
