# Generated by Django 4.0.4 on 2022-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0008_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
