# Generated by Django 4.0.4 on 2022-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0012_members_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='asso_image',
            field=models.ImageField(null=True, upload_to='image/blackbeltholder'),
        ),
    ]
