# Generated by Django 4.0.4 on 2022-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0012_members_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='asso_image',
            field=models.ImageField(null=True, upload_to='image/blackbeltholder'),
        ),
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_title', models.CharField(max_length=25)),
                ('con_content', models.TextField()),
                ('cont_img', models.ImageField(upload_to='image/blackbeltholder')),
            ],
        ),
    ]
