# Generated by Django 4.0.4 on 2022-06-27 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0013_members_asso_image'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='moreconts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_cont', models.TextField()),
                ('more_img', models.ImageField(upload_to='image/blackbeltholder')),
                ('con_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cont', to='karatte_org.contents')),
            ],
        ),
    ]
