# Generated by Django 4.0.4 on 2022-06-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0014_carousel_contents_pdfimg_register_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreconts',
            name='con_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cont', to='karatte_org.contents'),
        ),
    ]
