# Generated by Django 4.0.4 on 2022-06-24 18:24

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0014_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='videos',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='affiliation_img',
            field=models.ImageField(null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
