# Generated by Django 4.0.4 on 2022-07-18 05:41

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0016_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='check_register_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_reg_name', models.CharField(max_length=25)),
                ('check_reg_gender', models.CharField(max_length=10)),
                ('check_reg_bloodg', models.CharField(max_length=10)),
                ('check_reg_dob', models.CharField(max_length=20)),
                ('check_reg_national', models.CharField(max_length=15)),
                ('check_reg_occup', models.CharField(max_length=20)),
                ('check_reg_qualific', models.CharField(max_length=20)),
                ('check_reg_phon', models.CharField(max_length=15)),
                ('check_reg_email', models.EmailField(max_length=254)),
                ('check_reg_doj', models.CharField(max_length=20)),
                ('check_reg_pgname', models.CharField(max_length=20)),
                ('check_reg_pgoccu', models.CharField(max_length=20)),
                ('check_reg_address', models.CharField(max_length=50)),
                ('check_reg_reson', models.CharField(max_length=50)),
                ('check_reg_exp', models.CharField(max_length=5)),
                ('check_reg_op', models.CharField(max_length=5)),
                ('check_reg_img', models.ImageField(upload_to='image/blackbeltholder')),
            ],
        ),
        
        
    ]
