# Generated by Django 4.0.4 on 2022-07-18 12:04

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0018_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_register_members',
            name='check_status',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
       
    ]
