# Generated by Django 4.0.4 on 2022-07-22 07:29

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0019_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='HistoyrPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histry_img', models.ImageField(upload_to='image/blackbeltholder')),
            ],
        ),
       
    ]
