# Generated by Django 4.1 on 2022-08-16 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0021_about_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='regforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regpdf', models.FileField(upload_to='folderimages')),
                ('env_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karatte_org.news')),
            ],
        ),
        migrations.CreateModel(
            name='eventimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envimgpdf', models.FileField(upload_to='folderimages')),
                ('evnimg', models.ImageField(upload_to='folderimages')),
                ('envimage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karatte_org.news')),
            ],
        ),
    ]
