# Generated by Django 4.1 on 2022-08-17 17:30

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0022_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='members',
            name='mdesig',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='members',
            name='mname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='members',
            name='mposition',
            field=models.CharField(max_length=90),
        ),
    ]
