# Generated by Django 3.2.15 on 2022-08-23 11:31

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0023_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=30)),
                ('mail_id', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=30)),
                ('mesage', models.TextField()),
                ('enq_status', models.CharField(max_length=10)),
            ],
        ),
       
    ]
