# Generated by Django 3.2.15 on 2022-08-29 16:56

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0024_auto_20220823_1131'),
    ]

    operations = [
        
    ]
