# Generated by Django 3.2.15 on 2022-08-29 17:15

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0025_auto_20220829_1656'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='regforms',
            name='ev_subhead',
            field=models.CharField(default=35, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regforms',
            name='event_sub',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        
    ]
