# Generated by Django 4.1 on 2022-08-23 08:28

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0025_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
        
        
        
        migrations.DeleteModel(
            name='Enquery',
        ),
        
    ]
