# Generated by Django 4.1 on 2022-08-26 14:46

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0027_carousel_enquery_pdfimg_register_members_and_more'),
    ]

    operations = [
        
        
        
        
        
        
    ]
