# Generated by Django 4.1 on 2023-04-04 06:25

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0028_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
        
    ]
