# Generated by Django 4.1 on 2023-04-04 09:23

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0029_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
     
        migrations.AlterField(
            model_name='regforms',
            name='ev_subhead',
            field=models.CharField(max_length=255),
        ),
    ]
