# Generated by Django 4.1 on 2022-08-26 16:08

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0029_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
       
        
    ]
