# Generated by Django 4.1 on 2023-04-04 11:48

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0030_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
 
        migrations.AlterField(
            model_name='affilates_register',
            name='affvalid_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='affilates_register',
            name='affvalid_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
