# Generated by Django 4.1 on 2023-04-08 05:57

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0031_carousel_pdfimg_register_members_and_more'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='about',
            name='content_orid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affilates_register',
            name='register_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
       
    ]
